name: Deploy Hexo site to Pages

on:
  push:
    branches: [source]  # 监听 source 分支的推送
  workflow_dispatch:    # 允许手动触发部署

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 获取子模块（如果有的话）
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-blog-encrypt --save  # 安装加密插件
          npm install hexo-excerpt --save       # 安装摘要插件
      
      - name: Configure Hexo
        run: |
          # 添加摘要配置到 _config.yml
          echo "excerpt:" >> _config.yml
          echo "  depth: 200" >> _config.yml
          echo "  excerpt_excludes: []" >> _config.yml
          echo "  more_excludes: []" >> _config.yml
          echo "  hideWholePostExcerpts: false" >> _config.yml
      
      - name: Build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

